'use strict';
const COURSE_PT=window.COURSE;
const LANGUAGE_KEY='upnext-healthy-routines-language';
let language='en';
try{const savedLanguage=localStorage.getItem(LANGUAGE_KEY);if(['en','es','pt'].includes(savedLanguage))language=savedLanguage;}catch{}
try{const requestedLanguage=new URLSearchParams(location.search).get('lang');if(['en','es','pt'].includes(requestedLanguage))language=requestedLanguage;}catch{}
const UI_ROWS=[
['Pular para o conteúdo','Skip to content','Saltar al contenido'],
['Navegação principal','Main navigation','Navegación principal'],
['Meu curso','My course','Mi curso'],['Meu plano','My plan','Mi plan'],['Metodologia','Methodology','Metodología'],['Protótipo','Prototype','Prototipo'],
['Educação em saúde. No seu ritmo.','Health education. At your own pace.','Educación en salud. A tu ritmo.'],['Como construímos o curso','How we built the course','Cómo construimos el curso'],
['Recomeçar o protótipo?','Start the prototype over?','¿Volver a empezar el prototipo?'],['Isso apaga o progresso e as respostas salvas neste navegador.','This deletes progress and answers saved in this browser.','Esto elimina el progreso y las respuestas guardadas en este navegador.'],['Manter meus registros','Keep my records','Conservar mis registros'],['Apagar e recomeçar','Delete and start over','Eliminar y volver a empezar'],
['Um passo de cada vez','One step at a time','Un paso a la vez'],['Pequenas aulas.','Small lessons.','Lecciones breves.'],['Espaço para você.','Room for you.','Espacio para ti.'],
['Sono, alimentação, movimento e bem-estar. Explore uma ideia em cerca de dois minutos e leve um próximo passo para sua rotina.','Sleep, eating, movement and well-being. Explore an idea in about two minutes and take a next step into your routine.','Sueño, alimentación, movimiento y bienestar. Explora una idea en unos dos minutos y lleva un próximo paso a tu rutina.'],
['Cerca de 2 min por aula','About 2 min per lesson','Unos 2 min por lección'],['6 módulos independentes','6 independent modules','6 módulos independientes'],['No seu ritmo','At your own pace','A tu ritmo'],
['Seu percurso','Your journey','Tu recorrido'],[' de 30 aulas concluídas',' of 30 lessons completed',' de 30 lecciones completadas'],[' de 30 aulas exploradas',' of 30 lessons explored',' de 30 lecciones exploradas'],['Módulos do curso','Course modules','Módulos del curso'],['Uma semana por tema, se quiser.','One week per topic, if you like.','Una semana por tema, si quieres.'],[' de 5 aulas',' of 5 lessons',' de 5 lecciones'],['Módulo ','Module ','Módulo '],['5 microaulas','5 micro-lessons','5 microlecciones'],['Revisitar o módulo','Revisit the module','Revisitar el módulo'],['Continuar meu módulo','Continue my module','Continuar mi módulo'],['Começar este módulo','Start this module','Empezar este módulo'],['Rever','Review','Revisar'],
['Vamos conhecer sua rotina?','Let’s get to know your routine.','Conozcamos tu rutina.'],['Duas perguntas opcionais, sem resposta certa.','Two optional questions, with no right answer.','Dos preguntas opcionales, sin respuesta correcta.'],['Responder →','Answer →','Responder →'],['Uma ideia, um exemplo, uma pergunta e seu próximo passo.','One idea, an example, a question and your next step.','Una idea, un ejemplo, una pregunta y tu próximo paso.'],['Faça uma aula por dia ou escolha o ritmo que funciona para você.','Take one lesson a day or choose a pace that works for you.','Haz una lección al día o elige el ritmo que te funcione.'],['Conheça a metodologia →','Explore the methodology →','Conoce la metodología →'],
['Neste protótipo, progresso e respostas ficam apenas neste navegador. Não há envio à equipe ou sincronização entre dispositivos.','In this prototype, progress and answers stay in this browser. They are not sent to the team or synced across devices.','En este prototipo, el progreso y las respuestas quedan en este navegador. No se envían al equipo ni se sincronizan entre dispositivos.'],
['O armazenamento deste navegador está indisponível. Os registros ficam apenas nesta sessão.','Browser storage is unavailable. Records stay in this session only.','El almacenamiento del navegador no está disponible. Los registros quedan solo en esta sesión.'],
['Seu navegador não salvou os dados. Você pode continuar nesta sessão.','Your browser did not save the data. You can continue in this session.','Tu navegador no guardó los datos. Puedes continuar en esta sesión.'],
['Fechar a aula','Close lesson','Cerrar la lección'],['Etapa ','Step ','Etapa '],[' de 4',' of 4',' de 4'],[' · Aula ',' · Lesson ',' · Lección '],[' de 5',' of 5',' de 5'],
['Quero explorar um pouco mais','I would like to explore more','Quiero explorar un poco más'],['Uma ideia','One idea','Una idea'],['Ver um exemplo →','See an example →','Ver un ejemplo →'],['Como isso pode aparecer','How this might look','Cómo puede verse'],['no dia a dia','in everyday life','en la vida cotidiana'],['← Voltar','← Back','← Volver'],['Continuar →','Continue →','Continuar →'],['Escolha uma alternativa','Choose an answer','Elige una respuesta'],['Essa opção aplica a ideia da aula.','This option applies the lesson’s idea.','Esta opción aplica la idea de la lección.'],['Vamos olhar essa opção com calma.','Let’s look at this option together.','Veamos esta opción con calma.'],['Quero tentar outra alternativa','I would like to try another answer','Quiero probar otra respuesta'],['Meu próximo passo →','My next step →','Mi próximo paso →'],['Ver explicação','See explanation','Ver explicación'],['Leve uma ideia','Take an idea','Lleva una idea'],['para sua rotina','into your routine','a tu rutina'],['Seu próximo passo, se quiser','Your next step, if you like','Tu próximo paso, si quieres'],['Escreva do seu jeito. Você pode deixar para depois.','Write in your own words. You can leave this for later.','Escribe a tu manera. Puedes dejarlo para después.'],['Você pode experimentar e ajustar depois. O registro fica neste navegador; não precisa compartilhar detalhes de saúde.','You can try it and adjust later. The record stays in this browser; you do not need to share health details.','Puedes probar y ajustar después. El registro queda en este navegador; no necesitas compartir detalles de salud.'],['Pensar depois','Think about it later','Pensarlo después'],['Guardar e concluir','Save and finish','Guardar y completar'],
['Um passo explorado','One step explored','Un paso explorado'],['Você concluiu esta microaula.','You completed this micro-lesson.','Completaste esta microlección.'],['Você explorou as cinco ideias deste módulo. Pode revisitar qualquer uma quando quiser.','You explored all five ideas in this module. Revisit any of them whenever you like.','Exploraste las cinco ideas de este módulo. Puedes revisitar cualquiera cuando quieras.'],['Uma ideia para experimentar no seu dia. Você pode continuar agora ou voltar depois.','An idea to try in your day. You can continue now or return later.','Una idea para probar en tu día. Puedes continuar ahora o volver después.'],[' aulas exploradas neste módulo.',' lessons explored in this module.',' lecciones exploradas en este módulo.'],['Voltar ao meu curso','Return to my course','Volver a mi curso'],['Ver meu plano →','View my plan →','Ver mi plan →'],['Outra aula','Another lesson','Otra lección'],['Próxima microaula','Next micro-lesson','Próxima microlección'],
['Opcional · Sem resposta certa','Optional · No right answer','Opcional · Sin respuesta correcta'],['Sua rotina · Pergunta ','Your routine · Question ','Tu rutina · Pregunta '],[' de 2',' of 2',' de 2'],['Escolha uma opção','Choose an option','Elige una opción'],['A resposta serve para refletir sobre sua rotina. Neste protótipo, ela fica somente neste navegador.','Your answer helps you reflect on your routine. In this prototype, it stays in this browser only.','Tu respuesta ayuda a reflexionar sobre tu rutina. En este prototipo, queda solo en este navegador.'],['Pular esta pergunta','Skip this question','Omitir esta pregunta'],['Salvar e continuar →','Save and continue →','Guardar y continuar →'],
['Seu espaço de continuidade','Your space to keep going','Tu espacio para continuar'],['Um plano que pode','A plan that can','Un plan que puede'],['acompanhar sua vida.','fit your life.','acompañar tu vida.'],['Reúna seus próximos passos e escolha o que quer experimentar. Você pode rever, ajustar ou pausar.','Collect your next steps and choose what to try. You can review, adjust or pause.','Reúne tus próximos pasos y elige qué probar. Puedes revisar, ajustar o pausar.'],['Ideias que você guardou','Ideas you saved','Ideas que guardaste'],['Revisitar a aula','Revisit lesson','Revisitar la lección'],['Remover registro','Remove record','Eliminar registro'],['Seu plano começa com uma ideia.','Your plan starts with an idea.','Tu plan empieza con una idea.'],['Ao concluir uma microaula, você pode guardar um próximo passo aqui.','After completing a micro-lesson, you can save a next step here.','Al completar una microlección, puedes guardar aquí un próximo paso.'],['Explorar uma microaula →','Explore a micro-lesson →','Explorar una microlección →'],['Próximos 30 dias','Next 30 days','Próximos 30 días'],['Escolha uma ação para continuar.','Choose one action to continue.','Elige una acción para continuar.'],['Trinta dias é uma janela para experimentar, não um prazo obrigatório para formar um hábito.','Thirty days is a window for experimenting, not a required deadline for forming a habit.','Treinta días es una ventana para probar, no un plazo obligatorio para formar un hábito.'],['O que quero experimentar','What I want to try','Qué quiero probar'],['Quando ou depois de qual atividade','When or after which activity','Cuándo o después de qué actividad'],['Frequência que faz sentido para mim','A frequency that makes sense for me','Frecuencia que tiene sentido para mí'],['Uma alternativa para dias diferentes','An alternative for different days','Una alternativa para días diferentes'],['Quando quero revisar','When I want to review','Cuándo quiero revisar'],['Guardar meu plano','Save my plan','Guardar mi plan'],['Os campos são opcionais. Seus registros ficam apenas neste navegador.','Fields are optional. Your records stay in this browser only.','Los campos son opcionales. Tus registros quedan solo en este navegador.'],['Baixar meus registros','Download my records','Descargar mis registros'],['Apagar dados deste protótipo','Delete this prototype’s data','Eliminar los datos de este prototipo'],['Seu plano foi guardado neste navegador.','Your plan was saved in this browser.','Tu plan se guardó en este navegador.'],['Registro removido.','Record removed.','Registro eliminado.'],['Dados deste protótipo apagados.','Prototype data deleted.','Datos del prototipo eliminados.'],
['Ciência como base.','Science as a foundation.','La ciencia como base.'],['Sua rotina como contexto.','Your routine as context.','Tu rutina como contexto.'],['Healthy Routines combina educação em saúde, exemplos cotidianos e planejamento pessoal. Aqui estão as referências e os limites do que cada uma sustenta.','Healthy Routines combines health education, everyday examples and personal planning. Here are the references and the limits of what each supports.','Healthy Routines combina educación en salud, ejemplos cotidianos y planificación personal. Aquí están las referencias y los límites de lo que respalda cada una.'],['Como você aprende','How you learn','Cómo aprendes'],['Cada microaula apresenta uma ideia, um exemplo, um quiz com explicação e um próximo passo. As perguntas de rotina são opcionais e não recebem nota.','Each micro-lesson presents an idea, an example, a quiz with an explanation and a next step. Routine questions are optional and ungraded.','Cada microlección presenta una idea, un ejemplo, un quiz con explicación y un próximo paso. Las preguntas sobre tu rutina son opcionales y no tienen nota.'],['Cerca de dois minutos por aula e seis semanas de percurso são escolhas de design a testar. Não são durações cientificamente validadas.','About two minutes per lesson and a six-week journey are design choices to test. They are not scientifically validated durations.','Unos dos minutos por lección y seis semanas de recorrido son decisiones de diseño que se deben probar. No son duraciones validadas científicamente.'],['O que este programa oferece','What this program offers','Qué ofrece este programa'],['Educação geral sobre hábitos de sono, alimentação, movimento e bem-estar. A pessoa escolhe suas próprias ações e pode ajustar o plano.','General education about sleep, eating, movement and well-being habits. Participants choose their own actions and can adjust the plan.','Educación general sobre hábitos de sueño, alimentación, movimiento y bienestar. Cada persona elige sus acciones y puede ajustar el plan.'],['Referências por módulo','References by module','Referencias por módulo'],['Estudos empíricos, orientações públicas e decisões de design têm papéis diferentes. Nenhuma referência valida este curso como conjunto.','Empirical studies, public guidance and design decisions play different roles. No reference validates this course as a whole.','Los estudios empíricos, las orientaciones públicas y las decisiones de diseño cumplen funciones distintas. Ninguna referencia valida el curso en su conjunto.'],
['Conteúdo próprio e uso das fontes','Original content and use of sources','Contenido propio y uso de fuentes'],['As telas, exemplos fictícios, quizzes e atividades foram escritos para este programa. Citamos estudos e explicamos seus achados com redação própria, sem incorporar figuras, tabelas, escalas ou currículos de terceiros.','Screens, fictional examples, quizzes and activities were written for this program. We cite studies and explain findings in our own words without incorporating third-party figures, tables, scales or curricula.','Las pantallas, ejemplos ficticios, quizzes y actividades se escribieron para este programa. Citamos estudios y explicamos sus hallazgos con redacción propia, sin incorporar figuras, tablas, escalas ni planes de estudio de terceros.'],['Acesso gratuito a um artigo não significa permissão para reproduzir seus materiais comercialmente. As referências são links para as fontes originais, não publicações rebatizadas.','Free access to an article does not mean permission to reproduce its materials commercially. References link to original sources, rather than repackaged publications.','El acceso gratuito a un artículo no implica permiso para reproducir sus materiales comercialmente. Las referencias enlazan las fuentes originales, no publicaciones con otro nombre.'],['As fontes governamentais citadas estão disponíveis gratuitamente em seus sites. Citação ou link não indica endosso do curso ou da empresa por NIH, NCI, NIMH, NHLBI, FDA, CDC, HHS ou pelo governo dos Estados Unidos.','The government sources cited are freely available on their websites. A citation or link does not indicate endorsement of the course or company by NIH, NCI, NIMH, NHLBI, FDA, CDC, HHS or the U.S. government.','Las fuentes gubernamentales citadas están disponibles gratuitamente en sus sitios. Una cita o enlace no indica respaldo al curso o a la empresa por NIH, NCI, NIMH, NHLBI, FDA, CDC, HHS ni el gobierno de Estados Unidos.'],['Políticas de uso das fontes','Source use policies','Políticas de uso de las fuentes'],['NCI: uso de informação','NCI: information use','NCI: uso de información'],['NIMH: texto, imagens e publicações','NIMH: text, images and publications','NIMH: texto, imágenes y publicaciones'],['NHLBI: informação, marca e materiais','NHLBI: information, branding and materials','NHLBI: información, marca y materiales'],['CDC: condições e exceções','CDC: conditions and exceptions','CDC: condiciones y excepciones'],['As regras de domínio público têm condições e exceções. Não usamos os logos dessas instituições nem materiais visuais de terceiros.','Public-domain rules have conditions and exceptions. We do not use these institutions’ logos or third-party visual materials.','Las reglas de dominio público tienen condiciones y excepciones. No usamos los logos de estas instituciones ni materiales visuales de terceros.'],
['Seus registros neste protótipo','Your records in this prototype','Tus registros en este prototipo'],['Progresso, respostas e planos ficam salvos para sua conta neste navegador. Esses registros não são enviados à UpNext e não se sincronizam entre dispositivos. Você pode baixar seus registros ou apagá-los em Meu plano.','Progress, answers and plans are saved for your account in this browser. These records are not sent to UpNext or synced across devices. You can download or delete them in My plan.','El progreso, las respuestas y los planes se guardan para tu cuenta en este navegador. Estos registros no se envían a UpNext ni se sincronizan entre dispositivos. Puedes descargarlos o eliminarlos en Mi plan.'],['Surveys são perguntas próprias de reflexão, não escalas clínicas validadas. Nenhuma resposta gera diagnóstico ou acompanhamento de crise.','Surveys are original reflection questions, not validated clinical scales. No answer generates a diagnosis or crisis monitoring.','Los surveys son preguntas propias de reflexión, no escalas clínicas validadas. Ninguna respuesta genera diagnóstico ni seguimiento de crisis.'],['Se uma dificuldade persistir ou interferir no cotidiano, procure orientação profissional. Nos EUA, o 988 oferece apoio em crise de saúde mental; em risco imediato à vida, ligue 911.','If a difficulty persists or interferes with daily life, seek professional guidance. In the U.S., 988 provides mental health crisis support; call 911 for an immediate threat to life.','Si una dificultad persiste o interfiere en la vida diaria, busca orientación profesional. En EE. UU., el 988 ofrece apoyo en crisis de salud mental; ante riesgo inmediato para la vida, llama al 911.']
];
function t(text){if(language==='pt')return text;const row=UI_ROWS.find(r=>r[0]===text);return row?row[language==='es'?2:1]:text;}
const sortedUI=UI_ROWS.slice().sort((a,b)=>b[0].length-a[0].length);
function translateFragment(text){if(language==='pt')return text;const index=language==='es'?2:1;const tokens=[];for(const row of sortedUI){if(text.includes(row[0])){const token='\uE000'+tokens.length+'\uE001';text=text.split(row[0]).join(token);tokens.push(row[index]);}}return text.replace(/\uE000(\d+)\uE001/g,(_,n)=>tokens[+n]);}
function localizeHTML(html){
 if(language==='pt')return html;
 const protectedParts=[];
 // Personal writing must stay exactly as entered, in any interface language.
 html=html.replace(/<textarea\b[^>]*>[\s\S]*?<\/textarea>|<p\b[^>]*\bdata-user-text(?:="[^"]*")?[^>]*>[\s\S]*?<\/p>|\bvalue="[^"]*"/g,part=>{const token='\uE100'+protectedParts.length+'\uE101';protectedParts.push(part);return token;});
 // Translate visible text and accessible labels, never URLs, classes or code.
 html=html.replace(/(^|>)([^<]*)(?=<|$)/g,(_,prefix,text)=>prefix+translateFragment(text));
 html=html.replace(/\b(aria-label|placeholder)="([^"]*)"/g,(_,name,text)=>name+'="'+translateFragment(text)+'"');
 return html.replace(/\uE100(\d+)\uE101/g,(_,n)=>protectedParts[+n].replace(/placeholder="([^"]*)"/g,(_,text)=>'placeholder="'+translateFragment(text)+'"'));
}
function localizeElement(element){element.innerHTML=localizeHTML(element.innerHTML);}
const EVIDENCE_ROWS=[
['Planos que especificam situação e ação podem apoiar a realização de uma intenção.','Plans specifying a situation and action can support carrying out an intention.','Los planes que especifican una situación y una acción pueden apoyar la realización de una intención.'],
['Gollwitzer e Sheeran, Implementation Intentions, síntese teórica hospedada pelo NCI','Gollwitzer and Sheeran, Implementation Intentions, theoretical overview hosted by NCI','Gollwitzer y Sheeran, Implementation Intentions, síntesis teórica alojada por el NCI'],
['Tipo de fonte: Síntese teórica histórica. Página de referência sem manutenção atual. Não demonstra eficácia deste curso.','Source type: Historical theoretical synthesis. Reference page is no longer maintained. It does not demonstrate this course’s effectiveness.','Tipo de fuente: Síntesis teórica histórica. Página de referencia sin mantenimiento actual. No demuestra la eficacia de este curso.'],
['O estudo não encontrou superioridade de pistas de rotina sobre pistas de horário.','The study did not find routine-based cues superior to time-based cues.','El estudio no encontró superioridad de las señales de rutina frente a las de horario.'],
['Tipo de fonte: Ensaio randomizado. Estudou comportamentos alimentares cotidianos; não prova o mesmo efeito para todos os hábitos.','Source type: Randomized trial. It studied everyday eating behaviors and does not establish the same effect for all habits.','Tipo de fuente: Ensayo aleatorizado. Estudió conductas alimentarias cotidianas; no demuestra el mismo efecto para todos los hábitos.'],
['A automaticidade variou entre participantes; uma oportunidade perdida não alterou substancialmente o processo observado.','Automaticity varied across participants; one missed opportunity did not substantially alter the observed process.','La automaticidad varió entre participantes; una oportunidad perdida no alteró sustancialmente el proceso observado.'],
['Tipo de fonte: Estudo observacional longitudinal. Autorrelato e amostra específica. Não há prazo universal de formação de hábitos.','Source type: Longitudinal observational study. Self-reported data and a specific sample. There is no universal habit-formation deadline.','Tipo de fuente: Estudio observacional longitudinal. Autoinforme y muestra específica. No hay un plazo universal para formar hábitos.'],
['O NHLBI orienta reservar tempo para dormir e considerar horários, atividades noturnas e ambiente.','NHLBI recommends reserving time for sleep and considering schedules, evening activities and the environment.','El NHLBI recomienda reservar tiempo para dormir y considerar horarios, actividades nocturnas y entorno.'],
['Tipo de fonte: Orientação pública de educação em saúde. Não é estudo de eficácia deste módulo nem protocolo de tratamento de insônia.','Source type: Public health education guidance. It is not an effectiveness study of this module or an insomnia treatment protocol.','Tipo de fuente: Orientación pública de educación en salud. No es un estudio de eficacia del módulo ni un protocolo para tratar el insomnio.'],
['A porção do rótulo é referência dos valores apresentados, não recomendação individual de quanto consumir.','Label serving size is the reference for the values shown, not an individual recommendation about how much to consume.','La porción de la etiqueta es la referencia de los valores, no una recomendación individual de cuánto consumir.'],
['Tipo de fonte: Educação regulatória sobre rótulos dos EUA. Refere-se à rotulagem dos EUA; regras podem diferir em outros países.','Source type: Regulatory education about U.S. labels. It concerns U.S. labeling; rules may differ in other countries.','Tipo de fuente: Educación regulatoria sobre etiquetas de EE. UU. Se refiere a ese país; las reglas pueden variar en otros países.'],
['Comparar informação nutricional exige atenção às quantidades usadas como referência.','Comparing nutrition information requires attention to the reference amounts.','Comparar información nutricional requiere atención a las cantidades de referencia.'],
['Tipo de fonte: Educação regulatória sobre rótulos dos EUA. A comparação não estabelece uma dieta individual nem um alimento adequado para qualquer pessoa.','Source type: Regulatory education about U.S. labels. The comparison does not establish an individual diet or a food suitable for everyone.','Tipo de fuente: Educación regulatoria sobre etiquetas de EE. UU. La comparación no establece una dieta individual ni un alimento adecuado para todas las personas.'],
['As diretrizes apoiam mais movimento e menos tempo sentado, com atividade distribuída ao longo da semana.','Guidelines support more movement and less sitting, with activity distributed across the week.','Las directrices apoyan más movimiento y menos tiempo sentado, con actividad distribuida durante la semana.'],
['Tipo de fonte: Recomendação de saúde pública baseada em diretrizes. Uma pausa ou mudança de posição não equivale automaticamente a cumprir metas de atividade moderada ou fortalecimento.','Source type: Guideline-based public health recommendation. A break or change of position does not automatically meet moderate-activity or muscle-strengthening goals.','Tipo de fuente: Recomendación de salud pública basada en directrices. Una pausa o cambio de posición no equivale automáticamente a cumplir metas de actividad moderada o fortalecimiento.'],
['O NIMH inclui atividades agradáveis, prioridades e conexão social no autocuidado.','NIMH includes enjoyable activities, priorities and social connection in self-care.','El NIMH incluye actividades agradables, prioridades y conexión social en el autocuidado.'],
['Tipo de fonte: Orientação pública de educação em saúde. Autocuidado não substitui avaliação ou tratamento quando necessário.','Source type: Public health education guidance. Self-care does not replace evaluation or treatment when needed.','Tipo de fuente: Orientación pública de educación en salud. El autocuidado no sustituye la evaluación o el tratamiento cuando son necesarios.'],
['Aplicação no curso:','Application in this course:','Aplicación en el curso:'],
['a fonte apoia o princípio apresentado. A redação, o exemplo e a interação foram criados para este curso.','the source supports the principle presented. The wording, example and interaction were created for this course.','la fuente apoya el principio presentado. La redacción, el ejemplo y la interacción se crearon para este curso.'],
['esta atividade é uma escolha educativa original inspirada por um princípio mais amplo. A fonte não testou este exercício, esta frase nem uma microaula de dois minutos.','this activity is an original educational design choice inspired by a broader principle. The source did not test this exercise, wording or a two-minute micro-lesson.','esta actividad es una decisión educativa original inspirada por un principio más amplio. La fuente no probó este ejercicio, esta frase ni una microlección de dos minutos.']
];
function translatedEvidence(text,locale){for(const row of EVIDENCE_ROWS)text=text.split(row[0]).join(row[locale==='es'?2:1]);return text;}
const LESSON_FIELDS=['title','idea','example','question','options','feedback','action','deeper'];
function buildTranslation(raw,locale){return raw.map((m,i)=>({...m,lessons:m.lessons.map((row,j)=>Object.assign(Object.fromEntries(LESSON_FIELDS.map((field,k)=>[field,row[k]])),{correct:COURSE_PT[i].lessons[j].correct,evidence:translatedEvidence(COURSE_PT[i].lessons[j].evidence,locale)})),surveys:m.surveys.map(([question,options])=>({question,options}))}));}
const COURSES={pt:COURSE_PT,en:buildTranslation(window.COURSE_EN,'en'),es:buildTranslation(window.COURSE_ES,'es')};
function localeChrome(){document.documentElement.lang={en:'en',es:'es',pt:'pt-BR'}[language];document.title='Healthy Routines | UpNext';document.querySelector('meta[name="description"]').content={en:'UpNext Healthy Routines. Micro-lessons about sleep, eating, movement and well-being.',es:'Healthy Routines de UpNext. Microlecciones sobre sueño, alimentación, movimiento y bienestar.',pt:'Healthy Routines da UpNext. Microaulas sobre sono, alimentação, movimento e bem-estar.'}[language];document.getElementById('language').value=language;document.getElementById('language-label').textContent={en:'Language',es:'Idioma',pt:'Idioma'}[language];}
